"""Adding a soft delete

Revision ID: 3124a119c336
Revises: cc6f8bf5eceb
Create Date: 2026-05-23 18:52:16.202057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3124a119c336'
down_revision: Union[str, Sequence[str], None] = 'cc6f8bf5eceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('employees', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_active')
    op.drop_column('departments', 'is_active')
    # ### end Alembic commands ###
